waypointapp:
  build: .
  ports:
    - "5757:5757"
  environment:
    ENV: DEV
  volumes:
  # realdir:containerdir
  - ./app:/app
  # add "public folder here for shared drive"
  #- /mnt/srv/public:/public
  - ./data:/data

